FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

RUN npx prisma generate

ENV NODE_OPTIONS="--max-old-space-size=1536"
RUN npm run build

# Remove dev dependencies after build
RUN npm prune --omit=dev

# Clean npm cache
RUN npm cache clean --force

EXPOSE 3000

CMD ["node", "dist/src/index.js"]
